apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-be-app
spec:
  destination:
    name: ""
    namespace: shinnosuke-yoshizawa-checkride
    server: "https://kubernetes.default.svc"
  source:
    path: manifests
    repoURL: "https://github.com/shxn0/checkride-argocd-be.git"
    targetRevision: HEAD
    directory:
      recurse: true
  project: shinnosuke-yoshizawa-checkride
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions: []
