apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: shinnosuke-yoshizawa-argocd-app
  namespace: shinnosuke-yoshizawa-checkride-argocd

spec:
  project: shinnosuke-yoshizawa-checkride-argocd

  source:
    repoURL: https://github.com/shxn0/checkride-argocd-be.git
    targetRevision: HEAD
    path: dev
  destination:
    server: https://kubernetes.shinnosuke-yoshizawa-checkride-argocd.svc
    namespace: shinnosuke-yoshizawa-checkride-argocd
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
